### ISSUE TITLE
php sdk 里面leanpush.php里面的encode方法报错

### ISSUE THREAD

**Issue by holywei** [leancloud/php-sdk#101]
$query = $this->options["where"]->encode();这句有错

**Comment by holywei** [comment]
错误提示如下：
`Fatal error: Call to a member function encode() on array in D:\xampp\htdocs\yun\application\libraries\src\LeanCloud\LeanPush.php on line 149
A PHP Error was encountered

Severity: Error

Message: Call to a member function encode() on array

Filename: LeanCloud/LeanPush.php

Line Number: 149

Backtrace:`

**Comment by juvenn** [comment]
你好 @holywei ，

请注意 `LeanPush->setWhere($query)` 方法接收的参数只能是 `LeanQuery` 实例，请参考 API 文档：https://leancloud.cn/api-docs/php/class-LeanCloud.LeanPush.html#_setWhere

**Comment by juvenn** [comment]
由于没有进一步的反馈，先关闭这个 issue 了。如果还有问题可以在此评论。
