### ISSUE TITLE
支持调用服务端的云函数

### ISSUE THREAD

**Issue by juvenn** [leancloud/php-sdk#143]

**Comment by jysperm** [comment]
是这个问题么？ https://github.com/leancloud/cloud-code/issues/608

**Comment by juvenn** [comment]
是的，看来不同的用户有不同的需求。我这个用户是自己部署了  php 应用在阿里，然后需要调用到云引擎上 node.js 的云函数。

我在想支持一个  runRemote 来调用云引擎的云函数。
