### ISSUE TITLE
支持 app router

### ISSUE THREAD

**Issue by juvenn** [leancloud/php-sdk#155]

**Comment by BinaryHB** [comment]
稍后可以支持一下。

暂时只能分别在我们和 TAB 的文档进行强调：主站用 Client::useRegion("CN"); TAB 用 Client::useRegion("E1");
不能杜绝用户 Client::useRegion 时设置了错误节点所带来的问题。

**Comment by juvenn** [comment]
了解了一下 node-sdk 没有支持 app router ，因为 node-sdk 与命令行集成非常好，LEANCLOUD_API_SERVER 这个环境变量一定会配置。但 php-sdk 有些特殊，有用户会直接下载集成到自己的 php 项目，这时候就没有环境变量。所以 php-sdk 在没有环境变量的情况下，需要提供默认的 api url 。

**Comment by juvenn** [comment]
`useRegion` 的接口可能需要去掉，避免用户误用设置了 api server 。

**Comment by BinaryHB** [comment]
`useRegion ` 去掉了的话，PHP SDK 如何访问不同的节点呢？

**Comment by juvenn** [comment]
参考文档说明： https://github.com/leancloud/paas/wiki/%E6%8C%89%E7%85%A7%E5%BA%94%E7%94%A8%E5%92%8C%E6%9C%8D%E5%8A%A1%E6%8B%86%E5%88%86%E5%9F%9F%E5%90%8D%E8%AF%A6%E8%A7%A3
