### ISSUE TITLE
更新环境变量名称和其他 SDK 保持一致

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/php-sdk#157]
`LC_APP_ID` 更改为 `LEANCLOUD_APP_ID`
`LC_APP_KEY` 更改为 `LEANCLOUD_APP_KEY`
`LC_APP_MASTER_KEY`  更改为 `LEANCLOUD_APP_MASTER_KEY`

**Comment by jysperm** [comment]
补充一下，之前云引擎调整过提供的环境变量的前缀（`LC_` -> `LEANCLOUD_`），新的 SDK 都应该从后者读取信息。
