### ISSUE TITLE
请问PHP获取储存的数据表类后，如何以数组的形式输出呢

### ISSUE THREAD

**Issue by huaiyin0416** [leancloud/php-sdk#167]
![image](https://user-images.githubusercontent.com/32978395/35313700-be36da58-00fc-11e8-89a7-7d6d2aefd5a9.png)

**Comment by juvenn** [comment]
“以数组的形式”输出是指什么？在哪里输出？

另外，这里仅提供 sdk 开发方面的问题讨论。关于使用方面的问题，欢迎你到论坛里提问： https://forum.leancloud.cn/
