### ISSUE TITLE
PHP 7.2 - Cannot use 'LeanCloud\Object' as class name as it is reserved

### ISSUE THREAD

**Issue by burpsuite** [leancloud/php-sdk#173]
## Snapshot
![2018-04-24 17 53 03](https://user-images.githubusercontent.com/14309190/39180382-4d57190e-47e9-11e8-9801-c8821b8ac55e.png)

zh_CN: 不能使用“LeanCloud\Object”作为类的名字，因为它被保留
en_US: Cannot use 'LeanCloud\Object' as class name as it is reserved

## Description
* PHP 7.2 uses "Object" as typehint (https://wiki.php.net/rfc/object-typehint).

**Comment by burpsuite** [comment]
rename title.

**Comment by jysperm** [comment]
感谢反馈，我们在刚刚发布的 0.8.0 版本中将 Object 类改名为了 LeanObject，详见 https://github.com/leancloud/php-sdk/releases/tag/v0.8.0
