### ISSUE TITLE
Details: error:14090086:SSL routines

### ISSUE THREAD

**Issue by bruce-zzz** [leancloud/php-sdk#39]
Fatal error: Uncaught exception 'RuntimeException' with message 'CURL connection (https://us-api.leancloud.cn/1.1/date) error: 60 SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed' in C:\xampp\htdocs\aaa\vendor\leancloud\src\LeanCloud\LeanClient.php:362 Stack trace: #0 C:\xampp\htdocs\aaa\vendor\leancloud\src\LeanCloud\LeanClient.php(392): LeanCloud\LeanClient::request('GET', '/date', NULL, NULL, Array, NULL) #1 C:\D\xampp\htdocs\aaa\index.php(9): LeanCloud\LeanClient::get('/date') #2 {main} thrown in C:\xampp\htdocs\aaa\vendor\leancloud\src\LeanCloud\LeanClient.php on line 362

**Comment by juvenn** [comment]
这个是 windows 上的证书问题，请参考 #28 添加证书。

**Comment by bruce-zzz** [comment]
3q。

这个方法可用
解决办法是，在 php.ini 中指定证书：
[PHP]
curl.cainfo={path}/ca-bundle.crt
如果没有证书，可以参考这里来获取：http://curl.haxx.se/docs/caextract.html

另一个放system32下面不起作用

**Comment by juvenn** [comment]
:+1:  好的，谢谢反馈。
