### ISSUE TITLE
时间怎么设置时区？

### ISSUE THREAD

**Issue by bruce-zzz** [leancloud/php-sdk#40]
$v->get('birthdate');//这个字段是日期格式的
网页显示
birthdate :object(DateTime)#6 (3) { ["date"]=> string(19) "2015-12-25 08:11:09" ["timezone_type"]=> int(2) ["timezone"]=> string(1) "Z" }

怎么查询对应时区的时间？

**Comment by juvenn** [comment]
请参考 PHP 官方文档 `DateTime::setTimeZone`：http://php.net/manual/en/datetime.settimezone.php 。

另外，关于使用 SDK 方面的疑问或交流建议发到论坛哦：https://forum.leancloud.cn/c/jing-xuan-faq
