### ISSUE TITLE
$obj->save(); 报错 batchSave

### ISSUE THREAD

**Issue by bruce-zzz** [leancloud/php-sdk#41]
代码是这样的
$obj = new LeanObject("TestObject");
		$obj->set("name", "alice4");
		$obj->set("height", 60.0);
		$obj->set("weight", 4.5);
		$obj->set("birthdate", new \DateTime());
		try {
			$obj->save();
		} catch (CloudException $ex) {
			// CloudException 会被抛出，如果保存失败
			print_r($ex);
		}
错误信息
"code":401,"error":"Unauthorized."
LeanCloud\LeanObject.php
function:    batchSave
line:           631
class:         LeanCloud\LeanObject
请问这是神马情况？

**Comment by juvenn** [comment]
这是 app id 和 key 没有正确初始化，导致请求被拒绝。请注意正确初始化：

```php
// 参数依次为 app-id, app-key, master-key
LeanCloud\LeanClient::initialize("app_id", "app_key", "master_key");
```

**Comment by bruce-zzz** [comment]
这个弄过了呀，上面有这个东西， 我下面这个执行都是正常的，能正常注册用户
$user = new LeanUser();
		$user->setUsername("alice3");
		$user->setEmail("alice1@example.net");
		$user->setPassword("passpass");
		try {
			$user->signUp();
		} catch (CloudException $ex) {
			// 如果 LeanCloud 返回错误，这里会抛出异常 CloudException
			print_r($ex->getMessage());die;
		}

不知道为啥save()那个就不好用

**Comment by bruce-zzz** [comment]
"Batch requests error: [{"request":{"body":{"name":"alice","height":60,"weight":4.5},"method":"POST","path":"\/1.1\/classes\/TestObject"},"error":{"code":401,"error":"Unauthorized."}}]"

**Comment by bruce-zzz** [comment]
这是啥情况？怎么一会好用一会不好用呀。还是同一个Master Key  这个有请求限制？

**Comment by juvenn** [comment]
`$user->signUp` 后面也是调用的 save 方法，不应该出现 signUp 成功而 save 失败哎。你在确认一下 `LeanClient::initialize` 的参数里是否有多余的空格？

**Comment by juvenn** [comment]
你的第一个评论中的代码，我这边原封不动地测试也是成功的。
