### ISSUE TITLE
File save 语法错误

### ISSUE THREAD

**Issue by aquariuscool** [leancloud/php-sdk#46]
https://github.com/leancloud/php-sdk/blob/master/src/LeanCloud/LeanObject.php#L622

**Comment by juvenn** [comment]
谢谢报告问题，确认 bug 。会立即修复。

**Comment by juvenn** [comment]
已发布 `v0.2.2` 以解决这个 bug ：https://github.com/leancloud/php-sdk/releases/tag/v0.2.2
