### ISSUE TITLE
User 对象如果含有文件属性 则 getCurrentUser 会导致循环调用

### ISSUE THREAD

**Issue by bruce-zzz** [leancloud/php-sdk#48]
而且我的apache 的端口一直在变，这是神马情况
如果设置set_time_limit(0); 的话，就一直在转也不返回信息，貌似进入了死循环似得

登录的时候用LeanUser::logIn($name, $pass);，没有报错
获取当前用户 LeanCloud\LeanUser::getCurrentUser();这个的时候，
老是出现下面的错误，有没有办法处理
Fatal error: Maximum execution time of 30 seconds exceeded in LeanCloud\LeanClient.php on line 349

**Comment by bruce-zzz** [comment]
该文件 src/LeanCloud/LeanFile.php 60行有冲突，

我本来调用的就是LeanUser::getCurrentUser();  
到这里有调用了一遍，结果就进入了死循环，出不来了……

**Comment by juvenn** [comment]
确认为 bug ：如果 `LeanUser` 对象含有文件对象 `LeanFile`，`LeanUser::getCurrentUser` 会导致死循环。

```php
session_start();

$avatar = LeanFile::createWithUrl("alice.png", "example.com/alice.png");
$user = LeanUser::logIn("alice", "blabla");
$user->set("avatar", $avatar);
$user->save();

// 在下一个请求 getCurrentUser 将导致循环调用 getCurrentUser
seession_start();
$user = LeanUser::getCurrentUser();
```

会尽快修复，并发布。谢谢反馈。

**Comment by juvenn** [comment]
已发布修复版本 `0.2.3`: https://github.com/leancloud/php-sdk/releases/tag/v0.2.3
