### ISSUE TITLE
判断LeanClient是否已经初始化

### ISSUE THREAD

**Issue by edwardaa** [leancloud/php-sdk#73]
需要多次调用`LeanClient`的方法，调用前需要确保`LeanClient`已经初始化：`LeanClient->initialize()`。
希望增加一个方法，判断是否已经初始化：比如： `LeanClient->isInit()`.

另外多说一句：`LeanClient`更像一个实例对象，而不是一个工具类，所以static的方式不太合适；当然，重构的工作量较大 :)

**Comment by juvenn** [comment]
如果需要在独立的多个页面来调用 `LeanClient`，通常建议在页面的一开始就进行初始化。这样可以避免在每一个 `LeanClient` 调用的时候重复初始化的代码。

类似的需求似乎也并不常见，暂时不提供。后续如果收到更多反馈，我们会考虑提供。
