### ISSUE TITLE
_File mime_type 类型不匹配错误

### ISSUE THREAD

**Issue by yixtan** [leancloud/php-sdk#76]
![screen shot 2016-03-27 at 22 01 47](https://cloud.githubusercontent.com/assets/6598725/14065723/c5e65d1c-f467-11e5-8488-02676fde8f6a.png)
![screen shot 2016-03-27 at 22 01 56](https://cloud.githubusercontent.com/assets/6598725/14065725/ce45d69a-f467-11e5-8835-02f114dda764.png)

$file->save() 的时候会抛出错误

**Comment by juvenn** [comment]
谢谢反馈，能否提供错误堆栈以及文件名？

**Comment by yixtan** [comment]
object(LeanCloud\CloudException)#4 (7) {
  ["message":protected]=>
  string(106) "111 Invalid value type for field 'mime_type',expect type is {:type "Object"},but it is '{:type "String"}'."
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(111)
  ["file":protected]=>
  string(110) "******/vendor/leancloud/leancloud-sdk/src/LeanCloud/LeanClient.php"
  ["line":protected]=>
  int(335)
  ["trace":"Exception":private]=>
  array(4) {
    [0]=>
    array(6) {
      ["file"]=>
      string(110) "******/vendor/leancloud/leancloud-sdk/src/LeanCloud/LeanClient.php"
      ["line"]=>
      int(371)
      ["function"]=>
      string(7) "request"
      ["class"]=>
      string(20) "LeanCloud\LeanClient"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(6) {
        [0]=>
        string(4) "POST"
        [1]=>
        string(6) "/qiniu"
        [2]=>
        array(5) {
          ["name"]=>
          string(8) "test.txt"
          ["ACL"]=>
          NULL
          ["mime_type"]=>
          string(10) "text/plain"
          ["metaData"]=>
          array(2) {
            ["owner"]=>
            string(7) "unknown"
            ["size"]=>
            int(40)
          }
          ["key"]=>
          string(24) "ce947468d1e1e08de7fc.txt"
        }
        [3]=>
        NULL
        [4]=>
        array(0) {
        }
        [5]=>
        NULL
      }
    }
    [1]=>
    array(6) {
      ["file"]=>
      string(108) "******/vendor/leancloud/leancloud-sdk/src/LeanCloud/LeanFile.php"
      ["line"]=>
      int(371)
      ["function"]=>
      string(4) "post"
      ["class"]=>
      string(20) "LeanCloud\LeanClient"
      ["type"]=>
      string(2) "::"
      ["args"]=>
      array(2) {
        [0]=>
        string(6) "/qiniu"
        [1]=>
        array(5) {
          ["name"]=>
          string(8) "test.txt"
          ["ACL"]=>
          NULL
          ["mime_type"]=>
          string(10) "text/plain"
          ["metaData"]=>
          array(2) {
            ["owner"]=>
            string(7) "unknown"
            ["size"]=>
            int(40)
          }
          ["key"]=>
          string(24) "ce947468d1e1e08de7fc.txt"
        }
      }
    }
    [2]=>
    array(6) {
      ["file"]=>
      string(59) "******/test.php"
      ["line"]=>
      int(68)
      ["function"]=>
      string(4) "save"
      ["class"]=>
      string(18) "LeanCloud\LeanFile"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [3]=>
    array(4) {
      ["file"]=>
      string(59) "******/test.php"
      ["line"]=>
      int(75)
      ["function"]=>
      string(8) "saveFile"
      ["args"]=>
      array(0) {
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
}

控制台->存储->数据->_File 下面的 mime_type 是 object 型。刚开始学习 LeanCloud 和 php-sdk，遇到这个进行不下去了。

**Comment by juvenn** [comment]
文件创建是用的哪个接口？比如： `LeanFile::createWithData("test.txt", "Hello worl!")` ?

**Comment by yixtan** [comment]
WithDate 和 WithUrl 都不行，WithLocalFile 没有试

**Comment by juvenn** [comment]
mime_type 字段应该是字符类型的。你这里的问题，有可能是由于传递了不是字符的 $mimeType 参数，导致在第一次请求时创建了 mime_type 为 object 类型。这也导致后面正确的调用出现了类型不匹配的错误。

我们会尝试在 sdk  层面加入相关参数的检测，防止出现类似的错误。另请发邮件至 support@leancloud.cn ，提供你的 app-id ，并要求调整该字段类型。我们的同事收到邮件后，会进行处理。

**Comment by juvenn** [comment]
Todo:

* [ ] LeanFile 需要检测 mime_type 以防止数据字段被误设为非法类型

**Comment by juvenn** [comment]
可以通过控制台删除此列。sdk 暂不提供检测。
