### ISSUE TITLE
CURL connection (https://api.leancloud.cn/1.1/date) error: 28 28

### ISSUE THREAD

**Issue by wanminny** [leancloud/php-sdk#78]
按照你们官方提示，
运行一个简单的程序
/
    public function actionLean()
    {
// 参数依次为 appId, appKey, masterKey
        LeanClient::initialize("VR6qospg7s8JIq7eGMJ6GhnJ-gzGzoHsz", "qQLD81bSwGU1CNflkSJgP3fG", "IeuoNdKJHhCkHCxU46PcAUnY");

// 我们目前支持 CN 和 US 区域，默认使用 CN 区域，可以切换为 US 区域
//        LeanClient::useRegion("US");

         LeanClient::get("/date"); // 获取服务器时间
    }

起来后提示
RuntimeException
CURL connection (https://api.leancloud.cn/1.1/date) error: 28 28
看到后面官方文档说
1.如果遇到类似「Fatal error: Uncaught exception 'RuntimeException'...CURL connection...」的系统报错，请参考 修复 CURL connection 错误。
但是也没有看到解决方法；
2.说是CRT文件处理方法，我系统是MAC，而且这个CRT文件是怎么获取的？

**Comment by juvenn** [comment]
请注意确认你的 Mac 安装有 curl , 以及 php 的 curl 扩展。

**Comment by wanminny** [comment]
对的，这个已经安装了；PHPINOF方式和 php -m |grep curl 都有。

**Comment by wanminny** [comment]
ok 好了，谢谢·

**Comment by juvenn** [comment]
@wanminny 你好。注意到你的 issue 里泄漏了应用相关的 key 等信息，建议你到 LeanCloud 控制台对 key 进行重置。另外请参考：https://blog.leancloud.cn/4471/ 对你的应用进行安全性设置，以防止数据的不安全隐患。
