### ISSUE TITLE
LeanObject::save 失败的时候抛出确定的异常

### ISSUE THREAD

**Issue by aisk** [leancloud/php-sdk#79]
目前调用 save 时实际上时调用的 batchSave，如果发生异常的话，实际异常时保存在捕获异常的数组中的，实际上应该直接抛出这个异常。

**Comment by juvenn** [comment]
是的，然后在最后会抛出一个异常，并且会给出哪些请求失败了。这样做的初衷是方便用户定位具体请求的错误。

**Comment by juvenn** [comment]
确认了一下 python 的行为 https://github.com/leancloud/python-sdk/blob/master/leancloud/object_.py#L256 ，如果在 batch 请求中遇到错误，只是抛出了第一条错误。

**Comment by aisk** [comment]
Python 的实现其实有问题，我想在 batch 请求里面返回一系列的异常来着的……

batch 操作返回一系列异常我觉得是合理行为，但是 save 操作这么做感觉不太合适
