### ISSUE TITLE
Undefined index: token

### ISSUE THREAD

**Issue by fdddf** [leancloud/php-sdk#89]
US 上传文件发生错误

PHP Notice 'yii\base\ErrorException' with message 'Undefined index: token'

in /Users/aaaaa/Sites/CC/vendor/leancloud/leancloud-sdk/src/LeanCloud/LeanFile.php:372

Stack trace:
#0 /Users/aaaaa/Sites/CC/vendor/leancloud/leancloud-sdk/src/LeanCloud/LeanFile.php(372): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/aaaaa/S...', 372, Array)
#1 /Users/aaaaa/Sites/CC/console/controllers/UkRadioController.php(184): LeanCloud\LeanFile->save()
#2 [internal function]: console\controllers\UkRadioController->actionIntoCloud()
#3 /Users/aaaaa/Sites/CC/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#4 /Users/aaaaa/Sites/CC/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#5 /Users/aaaaa/Sites/CC/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('into-cloud', Array)
#6 /Users/aaaaa/Sites/CC/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('into-cloud', Array)
#7 /Users/aaaaa/Sites/CC/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('uk-radio/into-c...', Array)
#8 /Users/aaaaa/Sites/CC/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('uk-radio/into-c...', Array)
#9 /Users/aaaaa/Sites/CC/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 /Users/aaaaa/Sites/CC/yii(27): yii\base\Application->run()

**Comment by juvenn** [comment]
你好，很抱歉，美国区的文件上传 php sdk 还没有很好的支持。我们会在近期支持上传到 S3 。请在 #20 继续跟进相关进展。我们会以最高优先级来解决该问题。

如果是在开发测试阶段，建议你临时基于国内节点的应用来进行测试和开发。
